### ISSUE TITLE
New national leagues edited.

### ISSUE THREAD

**Issue by MazinkaiserZ** [kickoffworld/OpenPlayerManager#20]
happy new year and merry Xmas
During these days I've updated many leagues from Europe and other important extra-european leagues. When I've found few teams for a League (Armenia only 8 teams) , I've decided to add more nations together. 

The list: 
Portugal - Spain - France - England - Scotland & Wales - Ireland - Iceland & Far Oer - Finland - Sweden - Norway - Denmark - Russia - Ukraine - Belarus - Baltika (Lithuania+Estonia+Latvia) - Caucaso (Georgia+Armenia+Azerbaijian+Kazakhstan) - Belgium - Holland - France - Switzerland - Austria - Germany - Italy - Cyprus&Malta - Greece - Albania+Montenegro+Macedonia- Slovenia - Serbia - Croatia - Bosnia - Romania&Moldova - Bulgaria - Czech&Slovakia- Poland- Hungary - Turkey - Israel - minor (SMR+AND+LUX+GBL) - Argentina - Brazil - COMNEBOL (sudamerica no ARG no BRA) - CONCACAF - Mexico -  Africa - SouthAfrica - Australia - China - Japan -WestAsia - EastAsia- Saudi Arabia.

Of course, all these leagues cannot be inside "SQUADRE" as when U'll load a new League, the game will crush. (the max number is about 13-14 looks at the window)
So ... how can I add here so everybody can download it ?

**Comment by DannyCork** [comment]
Thanks. 

The irish.nams is very strange, lots of teams that don't make sense. How can I edit this ?

**Comment by MazinkaiserZ** [comment]
These are Irish teams. Ireland is a poor Champions in europe not very professional. Remember half teams are from northern Ireland, half from republic of Ireland.

**Comment by stainlessdmc12** [comment]
Do it Danny...
 do we have enough teams for both northern and southern Ireland?

**Comment by MazinkaiserZ** [comment]
I don't think U have an opened mind. Sourhern Ireland doesn't exist and the numbers of teams in these countries is low. Of course u can add the very professional team of the boys playing outside ur home.on't help u more. Bye

**Comment by MazinkaiserZ** [comment]
Ireland is only one island, one ppl even if thanks to church they kill their brothers.

**Comment by DannyCork** [comment]
*This is GitHub let's leave the political opinions at the door*.

Here are the teams for the Rep of Ireland

1.	Cork City	0	0	0	0	0:0	0	
 
2.	Shamrock Rovers	0	0	0	0	0:0	0	
 
3.	Drogheda	0	0	0	0	0:0	0	
 
4.	Sligo Rovers	0	0	0	0	0:0	0	
 
5.	Bray	0	0	0	0	0:0	0	
 
6.	St. Patricks	0	0	0	0	0:0	0	
 
7.	Bohemians	0	0	0	0	0:0	0	
 
8.	Derry City	0	0	0	0	0:0	0	
 
9.	Dundalk	0	0	0	0	0:0	0	
 
10.	Longford	0	0	0	0	0:0	0	
 
11.	Limerick	0	0	0	0	0:0	0	
 
12.	Galway

	Longford	28	18	6	4	56:19	60	     
2.	Shelbourne	28	14	10	4	46:30	52	     
3.	Galway	28	13	10	5	47:23	49	     
4.	Wexford	28	13	7	8	45:35	46	     
5.	Finn Harps	28	7	11	10	26:28	32	     
6.	Shamrock 2	28	7	5	16	25:50	26	     
7.	Waterford	28	6	7	15	25:43	25	     
8.	Cobh Ramblers

Thanks 20 teams, how many should be present in Player Manager.

**Comment by MazinkaiserZ** [comment]
43 are the teams in pm. 10+10+12+12 less your. This is not Eire or Ulster league as we cannot determine the correct number of teams in every league. As Irish UEFA seeding is very low we have dedecided to create a league with ur brothers in northern.

**Comment by MazinkaiserZ** [comment]
In pm2 remake this problem will be solved and there will be all 54 European countries.

**Comment by MazinkaiserZ** [comment]
After shower I will edit ur league... I will contact for someinfos like unknown teams jersey colors.

**Comment by DannyCork** [comment]
Look forward to it :)

**Comment by MazinkaiserZ** [comment]
sir in Ireland there are 12 teams in premiership and 8 in first division. I need 23 more, where can I find them?

**Comment by MazinkaiserZ** [comment]
Finished... there is Cherry Orchard too

**Comment by DannyCork** [comment]
Thanks. Where is the commit? Last one I see is Jan 7th ?

**Comment by MazinkaiserZ** [comment]
Ask to Filippo. Even if studied the Ireland story , I think the United championship with northern is better.

**Comment by DannyCork** [comment]
You said finished but there is no commit ?



Let's have an Italian league combined with an Libyan league or some former Italian colony?

Seriously, why should anyone bother with this project with all the politics and grief i?

**Comment by MazinkaiserZ** [comment]
Eire galaeic name of Rep. Of Ireland. Celtic lands

**Comment by MazinkaiserZ** [comment]
Italy is the 3rd European championship in Europe history. We have 100 professional teams. But Ireland is very poor as the best players leave it to play in English leagues. And Ireland is only 1 land , north or Eire the same names, traditions, blood. Think I have discovered Cm0102 have edited an Irish single league too

**Comment by filippodb** [comment]
@DannyCork   MazinkaiseZ has no glue on how to commit his work, I just commit all international championships.
@MazinkaiserZ please be patient, irish people have a long great history and tradition.
don't even think to mix irish/eire/english league.

**Comment by MazinkaiserZ** [comment]
Eire League I did last day. it was hard to search the best amateur teams in this country. I think we need an editor for the number of team in each League and the number of National piramid levels. I did Nigeria, Tunisia, morocco, Algeria and egypt. File nams on my Pc.

**Comment by MazinkaiserZ** [comment]
Oh my God... There are some Welsh teams in England leagues. Some Danny Welsh could be disliked. Hey Cardiff City and Swansea are in Epl... Wrexham. I forgot Eire is a great ppl...sure they have the elf and gold under a rainbow. And a greenman. I have lost my glue.

**Comment by MazinkaiserZ** [comment]
I'd like explain more about the use of the glue. But I don't need it to snif as I'm just totally funny without. Ah ah. As I told before only a bastard can escape on another forum and shot poo on another people without he knows. If I have some problem with U, I don't go crying to my mum as U did. Remember who are you and don't bother more. Or that glue, I will make U eat.

**Comment by stainlessdmc12** [comment]
You are making no sense at all.

**Comment by MazinkaiserZ** [comment]
RU still thinkig to it ? Go sleeping it's late. We just know ur cards

**Comment by filippodb** [comment]
I mean "has no clue" not "glue", sorry, btw, I think this is becoming a big misunderstanding mess, we have all european championships now, including Ireland, Eire, england etc. etc. thanks to MazinkaiserZ

I think makinkaiserz did a great work on open player manager but he's a bit upset and overreacted after some criticisms, but he's a great guy.

btw we have now all european championships so the task is closed.

**Comment by MazinkaiserZ** [comment]
OK, I'm editing South American countries, then my work will be finished and I'll think to the new stadiums.
