### ISSUE TITLE
How to add teams,players etc... for a country

### ISSUE THREAD

**Issue by DannyCork** [kickoffworld/OpenPlayerManager#6]
How would I go about adding a country eg:Ireland

1)What files would I need to contribute ?Just 
country.nams
country.txt ? 

2) eng.txt looks like csv but what format is eng.nams ? It's not csv, tab delimited perhaps?

**Comment by MazinkaiserZ** [comment]
Send him my new edited Eire.nams. his only a stupid racist... Ira blood. Zombie

**Comment by filippodb** [comment]
everything is committed to open player manager, there's no need to attack each other...
no reason for italy vs irish fight, Italians are better on football, irish are better on rugby etc. etc.

**Comment by MazinkaiserZ** [comment]
Eire is better to drink Guinness beer. But life is espansive , thats Why I refused a PhD at Trinity College. Need a strong fellowship.

**Comment by MazinkaiserZ** [comment]
Adieu Cork idiot ... live good in your poor island before the next conflict. Ps: when U are on the forum tell the true. That Eire is too small to have a league on pm as need 43 teams and not only 20 semipro and just don't lie. I'd like replay on there but I'm not there.

**Comment by stainlessdmc12** [comment]
What the fuck are you talking about Mazinkaiser ?? Man calm down and stop attacking Danny with your racist rant.
Leave the Irish teams alone. He's done well there. You've done plenty. :/

Stainy.

**Comment by stainlessdmc12** [comment]
No, you're the idiot.. Running someone off with your idiotic rant. You need to apologise and calm down.

Stainy

**Comment by MazinkaiserZ** [comment]
This idiot told lies on ko forum. If he has some problems with green honors can go fuck. As I told him Eire has only 20 semipro teams so no league. His reaction for my Irish file is the most racist example never seen. I'm happy he leaves as this boy doesn't respect my work.

**Comment by stainlessdmc12** [comment]
why did you get involved with the Irish teams though?

**Comment by MazinkaiserZ** [comment]
I'm involved in all League added on this game baby. From USA to Australia. I cannot add directly my nams but only by Filippo. I'm tired to say always I've nothing against EIRE, there are just few teams. And I don't think is correct if we have a discussion go on another site and shoot poo against my work. But I'm a good boy so I've created EIRE and NIR nams so Danny can enjoy. On Facebook KOW U can see it with UR eyes.

**Comment by filippodb** [comment]
sorry guys, I had to remove some comments, Mazinkaiserz send me all the championships and I commit them to Open Player manager so everybody can download them and edit.

Please everybody calm down, mazinkaiserz is a great guy, we should thanks him for his great effort on open player manager (fields graphics, international championships etc,.)
but he also overreacted a bit too much...

**Comment by MazinkaiserZ** [comment]
Sta senza pensieri.
